FROM ruby:4.0.0-alpine3.23

WORKDIR /app

COPY Gemfile /app/Gemfile
COPY app.rb /app/app.rb
COPY config.ru /app/config.ru
COPY helper/request_helper.rb /app/helper/request_helper.rb
COPY helper/custom_controller.rb /app/helper/custom_controller.rb
COPY helper/custom_exporter.rb /app/helper/custom_exporter.rb

RUN gem install bundler
RUN bundle install
CMD bundle exec rackup config.ru -o 0.0.0.0 -p $PORT
