apiVersion: v1
kind: Service
metadata:
  name: {{ include "request-dumper.fullname" . }}
  labels:
    {{- include "request-dumper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: ruby-rack
  selector:
    {{- include "request-dumper.selectorLabels" . | nindent 4 }}
